import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ReverseString {
    
    public static void main(String[] args) {
        ReverseString str= new ReverseString();
    	System.out.println(str.reverseStr(str.AskUserForAString()));
    }
    
    public String reverseStr(String str1) {
		String str2="";
		for (int i=str1.length()-1;i>=0;i--)
		{
			str2+=String.valueOf(str1.charAt(i));
		}
		return str2;
	}
    
    public String AskUserForAString() {
    	Scanner in= new Scanner(System.in);
    	System.out.println("Enter the string");
		return in.nextLine();
				
    }

}
