/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.io.ByteArrayInputStream;

public class ReverseStringTest {
	@DataProvider(name="palindromeCases")
    private Object[][] irrelevantName() {
        return new Object[][] {{"anna"},
                {"kayak"},
                {""},
                {"hannah"}};
    }

    @Test(dataProvider = "palindromeCases")
    public void reversedSometimesIsStillSame(String word) {
        // given
    	ReverseString classUnderTest = new ReverseString();

        // when
        final String reverse = classUnderTest.reverseStr(word);
        // then
        assertEquals(reverse, word);
    }
    
    @Test public void whetherReversedStringIstheSameEntered(){
		System.setIn(new ByteArrayInputStream("AllillA".getBytes()));
		ReverseString str = new ReverseString();
		String strGiven = str.AskUserForAString();
		String strReversed = str.reverseStr(strGiven);
		assertEquals(strGiven, strReversed, "Reversed string is the same as enteredd");
	}
}
